### ISSUE TITLE
Get sink connector listed at https://lenses.stream

### ISSUE THREAD

**Issue by vblagoje** [infinispan/infinispan-kafka#19]
https://www.landoop.com after merger with https://datamountaineer.com/ seems like the main platform for management of Kafka connectors and it would be great to get our connector listed at landoop/lenses i.e https://lenses.stream/connectors/sink-connectors.html and https://www.landoop.com/kafka/connectors/

**Comment by oscerd** [comment]
Really great idea. I'll take a look :-)

**Comment by oscerd** [comment]
It looks like all the connectors listed in landoop page are part of stream-reactor project from landoop

https://github.com/Landoop/stream-reactor/

So I don't think it is feasible to have our connector there.

**Comment by galderz** [comment]
More interesting would be to get https://www.confluent.io/product/connectors to list it :)

**Comment by oscerd** [comment]
yep :-) I'll take a look there too :-)

**Comment by oscerd** [comment]
I wrote to them :-)

**Comment by galderz** [comment]
Awesome! Keep us posted :)

**Comment by oscerd** [comment]
They raised a ticket internally to add this connector to the list

**Comment by vblagoje** [comment]
Cool, let's keep promoting this integration. I read more about Kafka connectors last night and I was really stoked about it.

**Comment by oscerd** [comment]
Yes, we can work also on the source connector from Infinispan to Kafka

**Comment by oscerd** [comment]
Listed

https://www.confluent.io/product/connectors/

**Comment by oscerd** [comment]
They removed the link.

**Comment by galderz** [comment]
@oscerd Can you email them and see what's up?

**Comment by oscerd** [comment]
Yes, sure. Lets see.

**Comment by oscerd** [comment]
It looks like they changed the policy to have the connector listed. 

https://docs.confluent.io/current/connect/managing/confluent-hub/contributing.html

So we may need to send an email again, I don't know about the Confluent terms of use.

**Comment by galderz** [comment]
@oscerd Ok. Can you try resubmitting? We're ASL2.

**Comment by oscerd** [comment]
@galderz sure, I'll keep you posted.

**Comment by gustavonalle** [comment]
We need to release an extra zip using their plugin ( e.g. https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/pom.xml#L129) and keep our artifacts as is, so I think no major changes are required in the connector itself, worth a try.

**Comment by oscerd** [comment]
Ok, I'll work on this in the next weeks
