### ISSUE TITLE
Pre-release adjustments

### ISSUE THREAD

**Issue by gustavonalle** [infinispan/infinispan-kafka#8]
Project is ready for releasing, but it'd be better to do a few adjustments to avoid issues down the line:

* Use version  ```0.1``` instead of ```0.0.1```, just to align with the other Infinispan connectors;
* Typo in the README.md: instead of "actually", use "currently"
* It'd be better to use a multi-module project where the current code would be located under ```core``` module name; the artifact can still have the same GAV as now. This allows to add new modules such as samples, tutorials and other optional jars. For an example of this structure, check https://github.com/infinispan/protostream/ or  https://github.com/infinispan/infinispan-hadoop/

**Comment by oscerd** [comment]
Sure thing, I'm gonna fix these things.
